version: 2.1

commands:
  install_java_package:
    steps:
      - run:
          name: Cài đặt nodejs package
          command: |
            sudo apt-get update
            sudo apt-get install nodejs npm git -y
            sudo apt-get install python3 python3-pip -y
            pip3 install paramiko requests
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - install_java_package
      - run:
          name: "Build frontend admin toeic app"
          command: |
            git clone https://github.com/ngthvan1612/ToeicAdminDashboardFE
            cd ToeicAdminDashboardFE
            npm i
            npm run build
            zip -r fe.zip build
            python3 ./.deploy/ssh.py
workflows:
  build_pipeline:
    jobs:
      - build:
          filters:
            branches:
              only:
                - deployment
